INSERT INTO tb_game_list (name) VALUES ('Aventura e RPG');
INSERT INTO tb_game_list (name) VALUES ('Jogos de plataforma');

INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Mass Effect Trilogy', 4.8, 2012, 'Role-playing (RPG), Shooter', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/1.png', 'A Mass Effect Trilogy (2012) combina os tres jogos da serie, envolvendo o Comandante Shepard na luta contra os Reapers, com escolhas impactantes.', 'A Mass Effect Trilogy de 2012 e uma coletanea de jogos de ficcao cientifica e RPG desenvolvida pela BioWare e publicada pela Electronic Arts. Essa trilogia compila os tres jogos principais da serie Mass Effect, lancados ao longo de varios anos, e oferece uma experiencia completa da saga do Comandante Shepard para os jogadores. A serie e ambientada em um vasto universo de ficcao cientifica, onde os jogadores exploram uma galaxia cheia de racas alienigenas, planetas diversos e uma ameaca cosmica chamada Reapers. Os jogadores assumem o papel do Comandante Shepard, um heroi personalizavel, e enfrentam escolhas morais, politicas e eticas que moldam a narrativa e o destino da galaxia.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Red Dead Redemption 2', 4.7, 2018, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/2.png', 'Red Dead Redemption 2 (2018) e um jogo de acao-aventura no Velho Oeste com Arthur Morgan, um mundo aberto, personagens ricos e historia envolvente.', 'Red Dead Redemption 2 e um jogo de acao-aventura desenvolvido pela Rockstar Games e lancado em 2018. O jogo e uma prequela do titulo anterior, seguindo a historia de Arthur Morgan, um fora da lei e membro da gangue de Dutch van der Linde. Ambientado no Velho Oeste americano em 1899, o jogo oferece uma vasta experiencia de mundo aberto, permitindo aos jogadores explorar paisagens deslumbrantes, cacar, interagir com personagens complexos e participar de uma narrativa envolvente.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('The Witcher 3: Wild Hunt', 4.7, 2014, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/3.png', 'The Witcher 3: Wild Hunt (2014) e um RPG de acao com Geralt de Rivia em um mundo de fantasia. Os jogadores exploram um vasto mundo aberto, enfrentam monstros e tomam decisoes cruciais enquanto buscam por sua filha adotiva, Ciri.', 'The Witcher 3: Wild Hunt e um jogo de RPG de acao desenvolvido pela CD Projekt Red e lancado em 2014. O jogo e ambientado em um mundo de fantasia sombria, onde os jogadores controlam Geralt de Rivia, um cacador de monstros conhecido como Witcher. A narrativa envolvente segue a busca de Geralt para encontrar sua filha adotiva Ciri e enfrentar uma misteriosa ameaca chamada Cacada Selvagem. O jogo oferece um vasto mundo aberto, repleto de missoes, monstros e escolhas morais que afetam o desenrolar da historia.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Sekiro: Shadows Die Twice', 3.8, 2019, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/4.png', 'Sekiro: Shadows Die Twice (2019) e um jogo de acao no Japao feudal, onde os jogadores controlam Wolf, um shinobi em busca de vinganca. A jogabilidade enfatiza combates de espada intensos e desafios que exigem precisao e habilidade.', 'Sekiro: Shadows Die Twice e um jogo de acao e aventura desenvolvido pela FromSoftware e publicado pela Activision em 2019. O jogo se passa no Japao feudal e segue a historia de Wolf, um shinobi em busca de vinganca apos o sequestro de um jovem lorde e seu proprio desmembramento. A jogabilidade e centrada no combate agil e estrategico, destacando-se por confrontos intensos de espada e a necessidade de precisao e habilidade para superar desafios. Sekiro tambem apresenta um mundo bem elaborado e um enredo complexo.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Ghost of Tsushima', 4.6, 2020, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/5.png', 'Ghost of Tsushima (2020) e um jogo de acao em um Japao feudal invadido pelos mongois. Jogadores controlam Jin Sakai, um samurai que se torna um "fantasma" para proteger sua terra, com cenarios deslumbrantes, combates de espada e escolhas morais.', 'Ghost of Tsushima e um jogo de acao de mundo aberto desenvolvido pela Sucker Punch Productions e lancado em 2020. Situado na ilha de Tsushima durante a invasao mongol do Japao feudal, o jogo segue a jornada de Jin Sakai, um samurai que se torna um "fantasma" para proteger sua terra natal. Os jogadores exploram um cenario deslumbrante, enfrentam inimigos em combates de espada e tomam decisoes morais que influenciam o destino de Jin. O jogo recebeu elogios por sua narrativa envolvente, jogabilidade desafiadora e a representacao autentica da cultura japonesa.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Super Mario World', 4.7, 1990, 'Platform', 'Super Ness, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/6.png', 'Super Mario World (1990) e um jogo de plataforma da Nintendo para o SNES. Mario embarca em uma jornada para resgatar a Princesa Peach de Bowser em Dinosaur Land, apresentando jogabilidade cativante e a estreia de Yoshi, o dinossauro.', 'Super Mario World e um jogo de plataforma desenvolvido e publicado pela Nintendo em 1990 para o console Super Nintendo Entertainment System (SNES). O jogo e uma continuacão da serie Mario e segue o encanador Mario em sua missao para resgatar a Princesa Peach do vilao Bowser, explorando o colorido mundo de Dinosaur Land. Super Mario World e aclamado por sua jogabilidade inovadora, niveis criativos e introducao do dinossauro Yoshi, que se tornou um personagem iconico na serie.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Hollow Knight', 4.6, 2017, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/7.png', 'Hollow Knight (2017) e um jogo de plataforma e acao do Team Cherry, onde os jogadores exploram Hallownest, enfrentam inimigos e desvendam segredos em um mundo subterraneo misterioso.', 'Hollow Knight e um jogo de plataforma e acao desenvolvido pelo Team Cherry e lancado em 2017. O jogo se passa em um mundo subterraneo sombrio e misterioso, onde os jogadores assumem o papel de um personagem sem nome, o Cavaleiro, que explora as profundezas de Hallownest para enfrentar criaturas hostis e desvendar segredos antigos. Com sua atmosfera envolvente, jogabilidade desafiadora e belos graficos desenhados a mao, Hollow Knight e amplamente elogiado por sua profundidade e complexidade.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Ori and the Blind Forest', 4, 2015, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/8.png', 'Ori and the Blind Forest (2015) e um jogo de plataforma e aventura da Moon Studios, com graficos desenhados a mao, trilha sonora emocional e desafios de plataforma envolventes.', 'Ori and the Blind Forest e um jogo de plataforma e aventura desenvolvido pela Moon Studios e lancado em 2015. O jogo segue a jornada de Ori, uma pequena criatura espiritual, enquanto explora um mundo magico e em perigo. Com graficos deslumbrantes desenhados a mao, trilha sonora emocional e uma narrativa comovente, Ori and the Blind Forest e elogiado por sua atmosfera unica e desafios de plataforma envolventes.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Cuphead', 4.6, 2017, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/9.png', 'Cuphead (2017) e um jogo de acao do Studio MDHR com estilo de arte retro dos anos 1930, onde os jogadores enfrentam chefes desafiadores.', 'Cuphead e um jogo de acao e tiroteio desenvolvido pelo Studio MDHR e lancado em 2017. O jogo se destaca por seu estilo de arte inspirado nas animacoes da decada de 1930, apresentando personagens carismaticos Cuphead e Mugman em uma busca para pagar uma divida com o diabo. Cuphead e conhecido por seus chefes desafiadores e jogabilidade de tiro classica, oferecendo uma experiencia unica que cativa os jogadores com sua estetica retro.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Sonic CD', 4, 1993, 'Platform', 'Sega CD, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/10.png', 'Sonic CD (1993) e um jogo de plataforma da Sonic Team que apresenta viagens no tempo. Os jogadores controlam Sonic em uma missao para resgatar Amy Rose de Dr. Robotnik em diferentes zonas do tempo, com trilha sonora envolvente e jogabilidade rapida.', 'Sonic CD e um jogo de plataforma desenvolvido pela Sonic Team e lancado em 1993. Ele faz parte da popular serie Sonic the Hedgehog da SEGA e destaca-se por apresentar viagens no tempo como um elemento central da jogabilidade. Os jogadores controlam Sonic enquanto ele tenta salvar Amy Rose do maligno Dr. Robotnik em diferentes zonas do tempo. Sonic CD e conhecido por sua trilha sonora cativante, graficos vibrantes e jogabilidade rapida e empolgante.');

INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 1, 0);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 2, 1);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 3, 2);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 4, 3);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 5, 4);

INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 6, 0);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 7, 1);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 8, 2);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 9, 3);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 10, 4);